import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Roboto_Slab } from "next/font/google";
import Provider from "./_trpc/Provider";
import { Toaster } from "@/components/ui/toaster";
export const metadata: Metadata = {
  title: "ToDo",
  description: "Generated by create next app",
};

const playFair = Roboto_Slab({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={playFair.className}>
          <Toaster />
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
